---
language: ruby
rvm:
- 2.6.4
sudo: false
cache: bundler
addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - libcurl4-openssl-dev
env:
- TASK='jekyll:check'
- TASK='jekyll:check_external_links'
#- TASK='spellcheck'
matrix:
  fast_finish: true
  allow_failures:
  - env: TASK='jekyll:check_external_links'
#  - env: TASK='spellcheck'
script: bundle exec rake $TASK
